<?php

/**
 * @file
 * Home of the MemCache instance manager class.
 */

/**
 * MemCache instance manager.
 */
class PsmInstanceMemcache extends PsmInstanceBase {

  /**
   * @return int
   */
  public function status($delay = FALSE) {
    // @todo: Implement start() method.
  }

  public function start() {
    // @todo: Implement start() method.
  }

  public function stop() {
    // @todo: Implement stop() method.
  }

  public function reload() {
    // @todo: Implement reload() method.
  }

  public function restart() {
    // @todo: Implement restart() method.
  }

}
